---
- name: Destroy entire infrastructure
  hosts: localhost
  connection: local
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Delete CNAME record for staging.domain
    route53:
      state: absent
      zone: "{{ route53_zone }}"
      record: "staging.{{ route53_zone }}"
      type: CNAME
      value: "{{ ec2_staging_instance_public_dns }}"
      ttl: 300

  - name: Terminate all EC2 instances
    ec2_instance:
      state: absent
      filters:
        instance-state-name: running
        tag:Name: Staging
      wait: yes

  - name: Delete Security Group for app instances
    ec2_group:
      group_id: "{{ ec2_sg_app_id }}"
      state: absent

  - name: Delete EC2 SSH key
    ec2_key:
      name: "{{ app_name }}"
      state: absent
