---
- name: Provision Staging instance
  hosts: localhost
  connection: local
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Launch Staging instance
    ec2_instance:
      name: Staging
      key_name: "{{ app_name }}"
      vpc_subnet_id: "{{ vpc_subnet_id_1 }}"
      instance_type: t2.micro
      security_group: "{{ ec2_sg_app_id }}"
      network:
        assign_public_ip: true
      image_id: "{{ ec2_al2_image_id }}"
      tags:
        Environment: Staging
      wait: yes
    register: staging_instance

  - name: Update variables file with instance public DNS
    lineinfile:
      path: etc/variables.yml
      regex: '^ec2_staging_instance_public_dns:'
      line: "ec2_staging_instance_public_dns: {{ staging_instance.instances[0].public_dns_name }}"
