#!/bin/bash

# Create temp files and define variables
tmpfile1=$(mktemp)
tmpfile2=$(mktemp)
day="$(date +%A)"
today="$(date +%Y%m%d)"
yesterday="$(date -d yesterday +%Y%m%d)"

# Concatenate recent log files together for processing
zcat /var/log/maillog-${yesterday}.gz > $tmpfile1
cat /var/log/maillog-${today} >> $tmpfile1

# Grep out subject lines as they cause problems
grep -v "warning: header Subject:" $tmpfile1 > $tmpfile2

# Run pflogsumm on yesterday's logs from processed log files and email results to tech team
/usr/sbin/pflogsumm -d yesterday --verbose_msg_detail --detail 20 --bounce_detail 20 --deferral_detail 20 --reject_detail 20 --smtpd_warning_detail 20 --no_no_msg_size $tmpfile2 | mail -s "Mail stats from $(hostname -s)" techteam@company.com

rm -f $tmpfile1 $tmpfile2
