---
- name: Harden CentOS 7 server (PHP & Apache changes)
  hosts: centosservers
  become: yes
  tasks:
  - name: Disable PHP functions
    lineinfile:
      path: /etc/php.ini
      regexp: '^disable_functions ='
      line: disable_functions = exec, system, shell_exec, passthru
  - name: Disable expose PHP
    lineinfile:
      path: /etc/php.ini
      regexp: '^expose_php ='
      line: expose_php = Off
  - name: Disable display errors in PHP
    lineinfile:
      path: /etc/php.ini
      regexp: '^display_errors ='
      line: display_errors = Off
  - name: Disable track errors in PHP
    lineinfile:
      path: /etc/php.ini
      regexp: '^track_errors ='
      line: track_errors = Off
  - name: Disable HTML errors in PHP
    lineinfile:
      path: /etc/php.ini
      regexp: '^html_errors ='
      line: html_errors = Off
  - name: Install Apache hardening config
    copy:
      src: httpd/hardening.conf
      dest: /etc/httpd/conf.d/hardening.conf
  - name: Install EPEL
    yum:
      name: epel-release
      state: present
  - name: Install ModSecurity & zip/unzip
    yum:
      name:
      - zip
      - unzip
      - mod_security
      state: present
  - name: Determine if OWASP ModSecurity Core Rule Set needs installing
    stat:
      path: /etc/httpd/owasp_crs
    register: owasp_crs
  - name: Download OWASP ModSecurity Core Rule Set
    get_url:
      url: https://github.com/coreruleset/coreruleset/archive/refs/heads/v3.3/master.zip
      dest: /tmp/crs.zip
    when: owasp_crs.stat.exists == False
  - name: Unzip CRS file
    unarchive:
      src: /tmp/crs.zip
      dest: /tmp
      remote_src: yes
    when: owasp_crs.stat.exists == False
  - name: Copy CRS folder
    copy:
      src: /tmp/coreruleset-3.3-master/
      dest: /etc/httpd/owasp_crs/
      remote_src: yes
    when: owasp_crs.stat.exists == False
  - name: Delete zip file
    file:
      path: /tmp/crs.zip
      state: absent
    when: owasp_crs.stat.exists == False
  - name: Delete tmp folder
    file:
      path: /tmp/coreruleset-3.3-master
      state: absent
    when: owasp_crs.stat.exists == False
  - name: Copy CRS conf file
    copy:
      src: /etc/httpd/owasp_crs/crs-setup.conf.example
      dest: /etc/httpd/owasp_crs/crs-setup.conf
      remote_src: yes
    when: owasp_crs.stat.exists == False
  - name: Delete old CRS conf file
    file:
      path: /etc/httpd/owasp_crs/crs-setup.conf.example
      state: absent
    when: owasp_crs.stat.exists == False
  - name: Add OWASP CRS rules to Apache config
    lineinfile:
      path: /etc/httpd/conf.d/mod_security.conf
      line: Include owasp_crs/rules/*.conf
      insertbefore: '^</IfModule>'
  - name: Add OWASP CRS conf to Apache config
    lineinfile:
      path: /etc/httpd/conf.d/mod_security.conf
      line: Include owasp_crs/crs-setup.conf
      insertbefore: '^Include owasp_crs/rules'
  - name: Install mod_evasive
    yum:
      name: mod_evasive
      state: present
  - name: Restart Apache
    service:
      name: httpd
      state: restarted
