---
- name: Delete dynamic variables, SSH key file, local Docker image and local app repo
  hosts: localhost
  connection: local
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Remove ELB DNS from variables file
    lineinfile:
      path: etc/variables.yml
      regex: '^elb_dns:'
      line: "elb_dns:"

  - name: Remove ELB Zone ID from variables file
    lineinfile:
      path: etc/variables.yml
      regex: '^elb_zone_id:'
      line: "elb_zone_id:"

  - name: Remove app Security Group from variables file
    lineinfile:
      path: etc/variables.yml
      regex: '^ec2_sg_app_id:'
      line: "ec2_sg_app_id:"

  - name: Remove LB Security Group from variables file
    lineinfile:
      path: etc/variables.yml
      regex: '^ec2_sg_lb_id:'
      line: "ec2_sg_lb_id:"

  - name: Remove ECR repo from variables file
    lineinfile:
      path: etc/variables.yml
      regex: '^ecr_repo:'
      line: "ecr_repo:"

  - name: Delete SSH key file
    file:
      path: etc/ec2_key.pem
      state: absent

  - name: Remove local Docker image
    docker_image:
      name: "{{ ecr_repo }}"
      state: absent
      force_absent: yes

  - name: Delete local app repo folder
    file:
      path: "./docker/{{ app_name }}"
      state: absent
