apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  replicas: 1
  service:
    type: LoadBalancer
  tls:
    secretName: rabbitmq-tls
    disableNonTLSListeners: true
  # Volume for importing RabbitMQ config definitions
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /definitions/
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions
  rabbitmq:
    additionalConfig: |
      load_definitions = /definitions/definitions.json
