---
- name: Deploy app on Staging instance
  vars:
    ansible_ssh_private_key_file: etc/ec2_key.pem
  hosts: tag_Environment_Staging
  remote_user: ec2-user
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Update OS
    become: yes
    yum:
      name: "*"
      state: latest

  - name: Install git
    become: yes
    yum:
      name: git-core
      state: latest

  - name: Create webapp folder
    become: yes
    file:
      path: /opt/simple_webapp
      state: directory
      owner: ec2-user
      group: ec2-user

  - name: Get app from GitHub
    git:
      repo: "https://github.com/mattbrock/simple_webapp.git"
      dest: /opt/simple_webapp
      force: yes

  - name: Copy systemd unit file to correct location
    become: yes
    copy:
      remote_src: yes
      src: /opt/simple_webapp/simple-webapp.service
      dest: /usr/lib/systemd/system/simple-webapp.service
      owner: root
      group: root

  - name: Reload systemd
    become: yes
    systemd:
      daemon_reload: yes

  - name: Enable and start service for app
    become: yes
    service:
      name: simple-webapp
      enabled: yes
      state: restarted
