---
- name: Provision a Target Group and an Application Load Balancer
  #vars:
  #  ansible_ssh_private_key_file: etc/ec2_key.pem
  #hosts: tag_Environment_Staging
  hosts: localhost
  connection: local
  #remote_user: ec2-user
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Provision Target Group
    elb_target_group:
      name: simple-webapp
      protocol: http
      port: 8080
      vpc_id: "{{ vpc_id }}"
      state: present
    register: target_group

  - name: Update variables file with Target Group ARN
    lineinfile:
      path: etc/variables.yml
      regex: '^elb_tg_arn:'
      line: "elb_tg_arn: {{ target_group.target_group_arn }}"
    when: target_group.changed

  - name: Provision Application Load Balancer
    elb_application_lb:
      name: simple-webapp
      security_groups: "{{ ec2_sg_lb_id }}"
      subnets:
      - "{{ vpc_subnet_id_1 }}"
      - "{{ vpc_subnet_id_2 }}"
      listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
        - Type: forward
          TargetGroupName: simple-webapp
