---
- name: Provision DNS
  hosts: localhost
  connection: local
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Create zone
    route53_zone:
      zone: "{{ route53_zone }}"
    register: dns_zone

  - name: Add an alias record for root
    route53:
      state: present
      zone: "{{ route53_zone }}"
      record: "{{ route53_zone }}"
      type: A
      value: "{{ elb_dns }}"
      alias: yes
      alias_hosted_zone_id: "{{ elb_zone_id }}"
      alias_evaluate_target_health: yes
      overwrite: yes

  - name: Add an alias record for www.domain
    route53:
      state: present
      zone: "{{ route53_zone }}"
      record: "www.{{ route53_zone }}"
      type: A
      value: "{{ elb_dns }}"
      alias: yes
      alias_hosted_zone_id: "{{ elb_zone_id }}"
      alias_evaluate_target_health: yes
      overwrite: yes

  - name: Add a CNAME record for staging.domain
    route53:
      state: present
      zone: "{{ route53_zone }}"
      record: "staging.{{ route53_zone }}"
      type: CNAME
      value: "{{ ec2_staging_instance_public_dns }}"
      ttl: 300
      overwrite: yes
