---
- name: Create AMI from Staging instance
  hosts: localhost
  connection: local
  tasks:

  - name: Import variables
    include_vars: etc/variables.yml

  - name: Determine if AMI already exists
    ec2_ami_info:
      filters:
        name: Staging
    register: ami_info

  - name: Delete AMI if it already exists, otherwise creation will fail
    ec2_ami:
      state: absent
      image_id: "{{ ami_info.images[0].image_id }}"
      delete_snapshot: yes
    when: ami_info.images[0].image_id is defined

  - name: Create AMI
    ec2_ami:
      instance_id: "{{ ec2_staging_instance_id }}"
      name: Staging
      tags:
        Name: Staging
      device_mapping:
      - device_name: /dev/xvda
        delete_on_termination: yes
      wait: yes
    register: staging_ami

  - name: Update variables file with AMI ID
    lineinfile:
      path: etc/variables.yml
      regex: '^ec2_staging_ami_id:'
      line: "ec2_staging_ami_id: {{ staging_ami.image_id }}"
    when: staging_ami.changed
