apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: artifact-registry
      containers:
      - name: my-app
        image: europe-west2-docker.pkg.dev/myproject/myrepo/my-app:latest
        imagePullPolicy: Always
